//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainingReleaseProgram
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string InvCode { get; set; }
        public string Program { get; set; }
        public string TR { get; set; }
        public Nullable<int> Type { get; set; }
        public string Course { get; set; }
        public string Status { get; set; }
        public bool IsRead { get; set; }
        public int CountRead { get; set; }
        public string CountReadtxt { get; set; }
    }
}
