//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainigModule
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Category { get; set; }
        public string TrainingType { get; set; }
        
        public string Topic { get; set; }
        public string Description { get; set; }
        public Nullable<int> StaffLevel { get; set; }
        public decimal Score { get; set; }
        public decimal ScorePr { get; set; }
        public Nullable<int> Target { get; set; }
        public string Document { get; set; }
        public string UrlDocument { get; set; }
        public string OtherDocument { get; set; }
        public string UrlOtherDocument { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public decimal Timer { get; set; }
        public string DayTerm { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string ChangedBy { get; set; }
        public string Createby { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
