//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainingExamHeader
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string ExamCode { get; set; }
        public string StaffID { get; set; }
        public string TrainingType { get; set; }
        public string Course { get; set; }
        public string Topic { get; set; }
        public string InvCode { get; set; }
        public Nullable<int> Type { get; set; }
        public string TopicDescription { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public decimal TotalModuleScore { get; set; }
        public decimal TotalScore { get; set; }
        public decimal TotalAchieve { get; set; }
        public int CorrectAnswer { get; set; }
        public int InCorrectAnswer { get; set; }
        public bool IsInitialTest { get; set; }
        public bool IsFinalTest { get; set; }
        public string Result { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
    }
}
