//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainingCourseItem
    {
        public string InvCode { get; set; }
        public int LineItem { get; set; }
        public Nullable<int> Type { get; set; }
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string Program { get; set; }
        public string Course { get; set; }
        public Nullable<int> Group { get; set; }
        public string Status { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Position { get; set; }
        public Nullable<int> StaffLevel { get; set; }
        public string NatID { get; set; }
        public string PhoneNo { get; set; }
        public bool IsDlrRead { get; set; }
        public decimal WorkExperience { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public int CountRead { get; set; }
        public string CountReadtxt { get; set; }
        public Nullable<System.DateTime> FirstAttance { get; set; }
        public Nullable<System.DateTime> LastAttance { get; set; }
    }
}
