//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TRELearningAnswer
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string AnswerCode { get; set; }
        public string CourseCode { get; set; }
        public string Topic { get; set; }
        public string TrainingType { get; set; }
        public string QuestionCode { get; set; }
        public decimal TotalScore { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public bool IsActive { get; set; }
        public int CheckValue { get; set; }
        public int ColumnCheck { get; set; }
        public int CorrectValue { get; set; }
    }
}
