//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training
{
    using Humica.EF.Models.SY;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TRTrainerType
    {
        
        public int TrainNo { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string SecDescription { get; set; }
        public string Remark { get; set; }
        public int LCK { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string ChangedBy { get; set; }
        private static List<TRTrainerInfo> TRTrainerInfos { get; set; }
        public string GetDescription => this.Code == TrainerType.INT ? "Internal" : "External";
        public int GetTotalTrainer => TRTrainerInfos.Where(w => w.TrainerTypeID == this.TrainNo.ToString()).Count();
        
        //public List<T> list { get; set; }
        public TRTrainerType(List<TRTrainerInfo> tRTrainerInfo)
        {
            TRTrainerInfos = new List<TRTrainerInfo>();
            tRTrainerInfo.ForEach(w => TRTrainerInfos.Add(w));
        }
        public TRTrainerType()
        {
            
        }
    }
}
