ALTER TABLE HRKPIPlanHeader drop CONSTRAINT PK_HRKPIPlanHeader
GO
ALTER TABLE HRKPIPlanHeader ADD CONSTRAINT [PK_HRKPIPlanHeader] PRIMARY KEY CLUSTERED
	(
		Code ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

