
CREATE TABLE [dbo].[HRARPPerformentRate](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FromRate] [decimal](18, 2) NOT NULL,
	[ToRate] [decimal](18, 2) NOT NULL,
	[Result] [int] NOT NULL,
 CONSTRAINT [PK_HRARPPerformentRate] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HRKPIAction]    Script Date: 5/6/2024 10:51:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO