CREATE TABLE [dbo].[HRKPIAction](
	[Code] [nvarchar](10) NOT NULL,
	[Description] [nvarchar](150) NOT NULL,
	[SecDescription] [nvarchar](200) NULL,
 CONSTRAINT [PK_HRKPIAction] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HRKPIList]    Script Date: 5/6/2024 10:51:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO