CREATE TABLE [dbo].[HRKPIList](
	[Code] [nvarchar](10) NOT NULL,
	[Description] [nvarchar](150) NOT NULL,
	[SecDescription] [nvarchar](200) NULL,
 CONSTRAINT [PK_HRKPIList] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO