CREATE TABLE [dbo].[SYSocialMedia](
  [ID] [int] IDENTITY(1,1) NOT NULL,
  [AccessToken] [nvarchar](350) NOT NULL,
  [Description] [nvarchar](250) NULL,
  [Type] [nvarchar](50) NULL,
 CONSTRAINT [PK_SYSocialMedia_1] PRIMARY KEY CLUSTERED 
(
  [ID] ASC,
  [AccessToken] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO